### ISSUE TITLE
Failed to configure external client

### ISSUE THREAD

**Issue by mansing2** [hazelcast-guides/kubernetes-external-client#7] opened 2021-02-16 11:20 UTC
Hi, I'm following the steps from https://guides.hazelcast.org/kubernetes-external-client/  but failing to form a cluster. 

1. When tried with a manual approach, the logs from one of the pods showing just one cluster pod, instead of three. 
2. When tried with Metacontroller approach, the deployment of service-per-pod.yaml is getting failed with an error "error: unable to recognize "service-per-pod.yaml": no matches for kind "DecoratorController" in version "metacontroller.k8s.io/v1alpha1""

Note - I'm using Nodeport

Any help is appreciated.

**Comment by SeriyBg** [comment] 2021-02-16 16:16
Hi @mansing2,
Seems like the second issue is related to the fact that the `metacontroller` files have been moved to another location, so these steps won't create the needed object, this should be changed in the guide as well:
```
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/metacontroller-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/metacontroller.yaml
```
Could you try to apply the following commands instead:
```
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller-crds-v1.yaml
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller.yaml
```

About the manual approach, I could not reproduce your issue. Could you please share the logs that are suspicious and the info about your env (minikube, could provider, etc.)?

**Comment by mansing2** [comment] 2021-02-16 17:09
@SeriyBg - About the manual approach, we have K8S on-premise and using Kubelet for all admin operations. The problem with this approach is the service does not get External IP.  I'm still checking it further. 

As suggested I tried with the above URLs, but when I tried deploying kubectl apply -f service-per-pod.yaml, getting the below error. 
error: unable to recognize "service-per-pod.yaml": no matches for kind "DecoratorController" in version "metacontroller.k8s.io/v1"

**Comment by grzesuav** [comment] 2021-02-16 22:22
https://github.com/hazelcast-guides/kubernetes-external-client/pull/8

@SeriyBg updated urls, also fixed on latest tag (1.4.2) to avoid confusion in future

**Comment by SeriyBg** [comment] 2021-02-17 08:36
@mansing2 could you please check that the CRD was created by running `kubectl get customresourcedefinitions | grep metacontroller`?
The output should be similar to:
```
compositecontrollers.metacontroller.k8s.io       2021-02-17T08:31:52Z
controllerrevisions.metacontroller.k8s.io        2021-02-17T08:31:52Z
decoratorcontrollers.metacontroller.k8s.io       2021-02-17T08:31:52Z
```

**Comment by mansing2** [comment] 2021-02-18 07:29
@SeriyBg  - I do get similar output as you copied when running the command kubectl get customresourcedefinitions | grep metacontroller.

Thank you @grzesuav @SeriyBg after deploying creds v1, (kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/master/manifests/production/metacontroller-crds-v1.yaml) I don't get any error. Good to close this.

**Comment by SeriyBg** [comment] 2021-02-18 08:31
Thank you @mansing2 for reporting the issue. Good to hear that it's resolved

**Closed as completed** 2021-02-18 08:31 UTC

**Comment by mansing2** [comment] 2021-02-18 08:55
@SeriyBg  - I have raised another issue https://github.com/hazelcast/hazelcast-kubernetes/issues/300 as lately I was also trying to setup on another K8S hosted on Google vms (not GKE). If you have any idea around that would help.
